/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildingInfoPanel: typeof import('./src/components/BuildingInfoPanel.vue')['default']
    BuildingPopup: typeof import('./src/components/BuildingPopup.vue')['default']
    CesiumViewer: typeof import('./src/components/CesiumViewer.vue')['default']
    CourseBubble: typeof import('./src/components/CourseBubble.vue')['default']
    CourseDetail: typeof import('./src/components/CourseDetail.vue')['default']
    CourseForm: typeof import('./src/components/CourseForm.vue')['default']
    CourseImport: typeof import('./src/components/CourseImport.vue')['default']
    CoursePanel: typeof import('./src/components/CoursePanel.vue')['default']
    EditPanel: typeof import('./src/components/EditPanel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HoverTooltip: typeof import('./src/components/HoverTooltip.vue')['default']
    LayerPanel: typeof import('./src/components/LayerPanel.vue')['default']
    MarsFlightPanel: typeof import('./src/components/mars/MarsFlightPanel.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PropertyTable: typeof import('./src/components/PropertyTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarContainer: typeof import('./src/components/SidebarContainer.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
