/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aspect: typeof import('./src/components/analysis/Aspect.vue')['default']
    Buffer: typeof import('./src/components/analysis/Buffer.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    ColorMap: typeof import('./src/components/ColorMap.vue')['default']
    Contour: typeof import('./src/components/analysis/Contour.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    GithubRepo: typeof import('./src/components/GithubRepo.vue')['default']
    HeightRestriction: typeof import('./src/components/analysis/HeightRestriction.vue')['default']
    Isosurface: typeof import('./src/components/analysis/Isosurface.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Model: typeof import('./src/components/Model.vue')['default']
    Profile: typeof import('./src/components/analysis/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sight: typeof import('./src/components/analysis/Sight.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
